spring.application.name=research-assistant
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=AIzaSyAR7myr4ebxZRpShBsOVVBvNN0JSMiIZwk
gemini.api.key="YOUR_API_KEY"

